name: "ultraviolet"

services:
  rails-app:
    labels:
      - dev.orbstack.domains=uv.local
      - dev.orbstack.ports=3000
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    depends_on:
      selenium:
        condition: service_started
      mail:
        condition: service_started
      postgres:
        condition: service_healthy

  selenium:
    labels:
      - dev.orbstack.domains=selenium.uv.local
    image: selenium/standalone-chromium
    restart: unless-stopped

  postgres:
    labels:
      - dev.orbstack.domains=db.uv.local
    image: postgres:16.1
    restart: unless-stopped
    networks:
      - default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 500ms
      retries: 5
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  mail:
    labels:
      - dev.orbstack.domains=mail.uv.local
      - dev.orbstack.http-port=1080
    image: marlonb/mailcrab:latest
    logging:
      driver: "none"
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  postgres-data:
